---
  # Title: ansible-role-xubuntu-core
  #
  # Author: Luc Rutten
  # Version: 1.0
  # File: tasks/main.yml
  #
  # Description:
  #   Providing a standerdized minimal-desktop based on xubuntu

#  - name: "For OS: Ubuntu 16.04LTS, Arch: amd64"
#    import_tasks: ubuntu-1604-amd64.yml
#    when:
#      - ansible_distribution_version == "16.04"
#      - ansible_architecture == "x86_64"

  - name: "For OS: Ubuntu 18.04LTS, Arch: amd64"
    import_tasks: ubuntu-1804-amd64.yml
    when:
      - ansible_distribution_version == "18.04"
      - ansible_architecture == "x86_64"

  - name: "Import xubuntu-core-networkmanager template (change to xubuntu networkmanager)"
    import_tasks: xubuntu-core-networkmanager.yml
    when:
      - ansible_distribution_version == "18.04"
      - ansible_architecture == "x86_64"

  - name: "Import cursor theme"
    import_tasks: xubuntu-core-cursor-theme.yml
    when:
      - xbc_cursor_state == "enabled"

  - name: "Import kioskmode template (Autologin)"
    import_tasks: xubuntu-core-kiosk.yml
    when:
      - xbc_kiosk_state == "enabled"

  - name: "Custom Plymouth splash logo"
    import_tasks: xubuntu-core-splashscreen.yml
    when:
      - xbc_splash_state == 'enabled'
