---
  # Title: ansible-role-desktop-minimal
  #
  # Author: Luc Rutten
  # Version: 1.0
  #
  # Description:
  #   Providing a standerdized minimal-desktop based on xubuntu

  - name: "Add repository key arc-theme"
    apt_key:
      url: https://download.opensuse.org/repositories/home:Horst3180/xUbuntu_16.04/Release.key 
      state: present

  - name: "Add repositories"
    apt_repository:
      repo: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - deb http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04/ /
      - ppa:numix/ppa

  - name: "Update apt cache"
    apt:
      update_cache: yes

  - name: "Install xubuntu-core"
    shell: apt-get install -y xubuntu-core^

  - name: "Install packages"
    apt:
      name: "{{ item }}"
      update_cache: yes
      force: yes
      state: present
    with_items:
      - arc-theme
      - numix-icon-theme-circle
      - fonts-roboto

  - name: "Create directory /opt/ansible-agent/"
    file:
      path: /opt/ansible-agent
      state: directory
     
  - name: "Create directory /opt/ansible-agent/scripts"
    file:
      path: /opt/ansible-agent/scripts
      state: directory

  - name: "Create directory /opt/ansible-agent/images"
    file:
      path: /opt/ansible-agent/images
      state: directory

  - name: "Copy startmenu icon  ubuntu-black-start.png to /opt/ansible-agent/images/ubuntu-black-start.png"
    copy:
      src: ubuntu-black-start.png
      dest: /opt/ansible-agent/images/ubuntu-black-start.png
      mode: 0755

  - name: "Copy startmenu icon wallpaper.jpg to /opt/ansible-agent/images/wallpaper.jpg"
    copy:
      src: "{{ xfconf_xfce4desktop_image_name }}"
      dest: "{{ xfconf_xfce4desktop_image_path }}"
      mode: 0755

  - name: "Copy template desktop-minimal-lightdm.conf.j2 to /etc/lightdm/lightdm.conf.d/desktop-minimal-lightdm.conf"
    template:
      src: 50-desktop-minimal-lightdm.conf.j2
      dest: /etc/lightdm/lightdm.conf.d/50-desktop-minimal-lightdm.conf
      mode: 0755

  - name: "Copy template desktop-minimal.sh.j2 to /opt/ansible-agent/scripts/desktop-minimal.sh"
    template:
      src: desktop-minimal.sh.j2
      dest: /opt/ansible-agent/scripts/desktop-minimal.sh
      mode: 0755 

  - name: "Add desktop-minimal.sh script to global login script /etc/xdg/autostart/desktop-minimal.desktop"
    copy:
      src: desktop-minimal.desktop
      dest: /etc/xdg/autostart/desktop-minimal.desktop

  - name: "Copy template terminalrc.j2 to /etc/xdg/xdg-ubuntu/xfce4/terminal/terminal.rc"
    template:
      src: terminalrc.j2
      dest: /etc/xdg/xdg-xubuntu/xfce4/terminal/terminalrc

  - name: "Create directory /etc/xdg/xfce4/kiosk"
    file:
      path: /etc/xdg/xfce4/kiosk
      state: directory

  - name: "Copy template kioskrc.j2 to /etc/xdg/xfce4/kiosk/kioskrc"
    template:
      src: kioskrc.j2
      dest: /etc/xdg/xfce4/kiosk/kioskrc
    
