---
  # Title: xubuntu-core-networkmanager.yml
  #
  # Author: Luc Rutten
  # Version: 1.0
  # File: tasks/xubuntu-core-kiosk.yml
  #
  # Description:
  #   Enable networkmanager on the server version
  #   to handle all connections.
  #
  # Sources:
  #   https://help.ubuntu.com/community/NetworkManager?action=show&redirect=WifiDocs%2FNetworkManager
  #   https://askubuntu.com/questions/842773/ubuntu-server-and-networkmanager
  #

  - name: "Install packages"
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - network-manager
      - network-manager-gnome
    when:  
      - xbc_network_manager_state == 'enabled'

  - name: "Transfer templates"
    template:
      src: 01-network-manager-all.yaml.j2
      dest: /etc/netplan/01-network-manager-all.yaml
      owner: root
      group: root
      mode: 0755
    when:
      - xbc_network_manager_state == 'enabled'

  - name: "Rename /etc/netplan/01-netcfg.yaml to /etc/netplan/01-netcfg.yaml.old"
    copy:
      src: /etc/netplan/01-netcfg.yaml 
      dest: /etc/netplan/01-netcfg.yaml.old
      owner: root
      group: root
      mode: 0755
      remote_src: yes
    ignore_errors: yes
    when:
      - xbc_network_manager_state == 'enabled'

  - name: "Remove original file"
    file:
      path: /etc/netplan/01-netcfg.yaml
      state: absent
    when:
      - xbc_network_manager_state == 'enabled'

  - name: "Restore to default: Rename /etc/netplan/01-netcfg.yaml.old to /etc/netplan/01-netcfg.yaml"
    copy:
      src: /etc/netplan/01-netcfg.yaml.old
      dest: /etc/netplan/01-netcfg.yaml
      owner: root
      group: root
      mode: 0755
      remote_src: yes
    ignore_errors: yes
    when:
      - xbc_network_manager_state == 'disabled'

  - name: "Restore to default: Remove /etc/netplan/01-network-manager-all.yaml"
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /etc/netplan/01-network-manager-all.yaml
      - /etc/netplan/01-netcfg.yaml.old
    when:
      - xbc_network_manager_state == 'disabled'

  - name: "Remove packages"
    apt:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - network-manager
      - network-manager-gnome
    when:
      - xbc_network_manager_state == 'disabled'
