---
  # Title: ansible-xubuntu-core
  #
  # Author: Luc Rutten / David Weng
  # Version: 1.0
  # File: tasks/ubuntu-core-splashscreen.yml
  #
  # Description:
  #  configure greenos splashscreen

  - name: "Creating in splashscreen directory in /usr/share/plymouth/themes"
    file:
      path: /usr/share/plymouth/themes/xubuntu-core-splash
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: "configure basic splashscreen settings"
    template:
      src: xubuntu-core-splash.plymouth.j2
      dest: /usr/share/plymouth/themes/xubuntu-core-splash/xubuntu-core-splash.plymouth
      owner: root
      group: root
      mode: 0755

  - name: "import template file with script"
    template:
      src: xubuntu-core-splash.script.j2
      dest: /usr/share/plymouth/themes/xubuntu-core-splash/xubuntu-core-splash.script
      owner: root
      group: root
      mode: 0755

  - name: "configure xubuntu-core-splash logo (url)"
    get_url:
      url: "{{ xbc_splash_image_url }}"
      dest: /usr/share/plymouth/themes/xubuntu-core-splash/xubuntu-core-splash.png
      force: yes
    when:
      - xbc_splash_state == 'enabled' and xbc_splash_type == 'url' 
    register: splash_url

  - name: "configure xubuntu-core-splash logo (file)"
    copy:
      src: "{{ xbc_splash_image_file }}"
      dest: /usr/share/plymouth/themes/xubuntu-core-splash/xubuntu-core-splash.png
    when:
      - xbc_splash_state == 'enabled' and xbc_splash_type == 'file'
    register: splash_file

  - name: "configure greensplash screen"
    shell: update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/xubuntu-core-splash/xubuntu-core-splash.plymouth 100
    when: splash_url is changed or splash_file is changed

  - name: "creating a symbolic link for greensplash"
    shell: update-alternatives --set default.plymouth /usr/share/plymouth/themes/xubuntu-core-splash/xubuntu-core-splash.plymouth
    when: splash_url is changed or splash_file is changed

  - name: "update plymouth boot loader"
    shell: update-initramfs -u
    when: splash_url is changed or splash_file is changed

