---
  # Title: ansible-role-desktop-minimal
  #
  # Author: Luc Rutten
  # Version: 1.0
  # File: tasks/xubuntu-core-autologin.yml
  #
  # Description:
  #   Enable autologin for kiosk mode

  - name: "Create autologin user"
    user:
      name: "{{ ldm_autologin_user }}"
      shell: /bin/bash
      group: users
      comment: user for autologon
      state: "{{ ldm_autologin_status }}"
         
  - name: "Copy template 60-autologin-lightdm.conf.j2 to /etc/lightdm/lightdm.conf.d/60-autologin-lightdm.conf"
    template:
      src: 60-autologin-lightdm.conf.j2
      dest: /etc/lightdm/lightdm.conf.d/60-autologin-lightdm.conf
      mode: 0755
    when:
      - ldm_autologin_status == "present"

  - name: "Remove file if exists /etc/lightdm/lightdm.conf.d/60-autologin-lightdm.conf"
    file:
      path: /etc/lightdm/lightdm.conf.d/60-autologin-lightdm.conf
      state: absent
    when:
      - ldm_autologin_status == "absent"
